columnSuffix: bzjcptdz
contentColumnType: text
fieldGroup: df6ced21-7500-4eae-b7ba-bd0668a28801 # BlogPosts
handle: postDescription
instructions: null
name: Description
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
